name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - deploy/production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        if: github.ref_name == 'main'
        run: npm install

      - name: Lint Code
        if: github.ref_name == 'main'
        run: npm run lint

      - name: Run Tests
        if: github.ref_name == 'main'
        run: npm run test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        if: github.ref_name == 'main'
        run: docker build --platform linux/amd64 -t ruslankotliar/ci-todo-backend:${{ github.sha }} .

      - name: Push Docker Image
        if: github.ref_name == 'main'
        run: docker push ruslankotliar/ci-todo-backend:${{ github.sha }}

      - name: Deploy to AWS EC2
        if: github.ref_name == 'deploy/production'
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd app
            sed -i '/^BACKEND_TAG=/d' .env  # Remove existing BACKEND_TAG if present
            echo "BACKEND_TAG=${{ github.sha }}" >> .env  # Add or update BACKEND_TAG
            docker compose pull backend
            docker compose up -d backend

      # Uncomment this step to test failure notification
      # - name: Test Failure
      #   run: exit 1 # Force a failure for testing purposes

  notify:
    if: failure()
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            "channel": "${{ secrets.SLACK_BACKEND_CHANNEL_ID }}",
            "text": "🚨 GitHub Actions: Backend CI/CD pipeline failed for branch ${{ github.ref_name }}."
